learning_templates/basic_app/urls.py
from django.urls import path
from . import views #similar to from basic_app import views

# SET THE NAMESPACE, fot template tagging
app_name = 'basic_app'

urlpatterns=[
    path('relative/',views.relative,name='relative'),
    path('other/',views.other,name='other'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index,name='index'),#if someoe goes to homepage grab index page and show it to him
    path('basic_app/', include('basic_app.urls')),#if someone goes to webpage/basicapp/etc we tell him go to basc_app.urls for what to show
    path('admin/', admin.site.urls),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
	context_dict={'text':"hello world", 'number':100}
	return render(request,'basic_app/index.html',context_dict)
	
	
def other(request):
	return render(request,'basic_app/other.html')	
	
	
def relative(request):
	return render(request,'basic_app/relative_url_templates.html')	
	
	

learning_templates/basic_app/templates/basic_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
        <a class="nav-item nav-link" href="{% url 'basic_app:other' %}">Other</a>
      </div>
    </nav>

    <div class="container">
    {% block body_block %}
    {# Anything outside of this will be inherited if you use extend.#}
    {% endblock %}
    </div>

  </body>
</html>

learning_templates/basic_app/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% load my_extras %}

    {% block body_block%}

    <h1>Hello and welcome to the site!</h1>
    <h1>This is the index.html page !</h1> 
    <h1>{{ text|upper }}</h1>
	    <h1>{{ text|cutout:"hello" }}</h1>
    <h1>{{ number|add:99 }}</h1>
    {% endblock %}

learning_templates/basic_app/templates/basic_app/other.html
<!DOCTYPE html>
<html>
{% extends "basic_app/base.html" %}
    {% block body_block %}
    <h1>This is an example of template inheritance!</h1>
    <h2>Officially this is the other.html page!</h2>
    {% endblock %}
</html>

learning_templates/basic_app/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Relative Urls</title>
  </head>
  <body>
    <h1>Welcome to relative url!</h1>
    <p>
      This page serves as an example of how to
      use relative urls with templates!
      This is the relative_url_templates.html file.
    </p>

    {# Here are the examples:#}
    {# Must set the app_name=basic_app variable inside the basic_app/urls.py#}
    <a href="{% url 'admin:index' %}">Link to Admin Page</a>

    <a href="{% url 'basic_app:other' %}">Link to other.html</a>
    <a href="{% url 'index' %}">Link to index.html</a>

  </body>
</html>